### ISSUE TITLE
default password

### ISSUE THREAD

**Issue by jeffmpeebles** [Paulus88/Pi-hole-on-MicroK8s#1]
I can't login, nor do i know how to change the password since this is in a container.

**Comment by Paulus1337** [comment]
Hi @jeffmpeebles!

Wow good spot, I totally forgot to mention that.
To set your password the first time use environment veriable:
WEBPASSWORD.

Otherwise it will generate a random password which can be found in each containers log.
If you do the WEBPASSWORD environment veriable once so it saves the password in your data files after that in my case I remove this veriable once all containers recieved it.

Let me add that to my YAML with password:
Welcome

**Comment by Paulus1337** [comment]
Hi @jeffmpeebles,

I updated the yaml to add the Default Password, and added instructions.
Is this helpful?

**Comment by jeffmpeebles** [comment]
Perfect.  Thanks for all of this.
